### ISSUE TITLE
Daily Report Logic

### ISSUE THREAD

**Issue by gigihiski** [Etsuriltd/Mang-Udin-Bot#13]
Daily Report Login Flow:
1. Find latest order on question table from given slackId ( user who currently write a report )
`SELECT order from question as table1 JOIN answer as table2 on (t1.id = t2.questionId) where t2.slack_id = {current_slack_id} and t2.createdAt = date(today)`
2. Save current answer to database
3. Repeat step no 1 and stop giving question when last order on question table is equal to total questions

**Comment by wahyusumartha** [comment]
for step number 3, we can add formatted `Thank  You` message when we should stop giving next question, which means the user has done with their report
