### ISSUE TITLE
Custom Reminder Feature

### ISSUE THREAD

**Issue by gigihiski** [Etsuriltd/Mang-Udin-Bot#6]
users can create custom reminder or even can send an attachment to email or selected slack users

**Comment by wahyusumartha** [comment]
What kind of custom reminder that you propose ?
Could you elaborate more,  please ?
I prefer to have very specific proposal here, ;)

**Comment by gigihiski** [comment]
so Mang Udin should create a reminder (task or event) for user itself or people they have tagged into it and save it to google calendar.
i.e.
/remind 'me and @wahyusumartha to send a note to mail@example.com tomorrow at 10am'
and Mang Udin will send us a notification tomorrow at 10am, or if its possible Mang Udin can automatically send the note to mail@example.com :)

**Comment by wahyusumartha** [comment]
i think it's kind of duplicate with what the bot does, 
why don't we make it more specific ? 
Create a feature to create an invoice for example , rather than just a reminder ;) 

@gigihiski What do you think ?

**Comment by wahyusumartha** [comment]
@gigihiski we could closed this issue, and come out with another issue that is more specific
